OTS/urls.py
from django.urls import path
from OTS.views import *

app_name='OTS'
urlpatterns = [
    path('', welcome),
    path('new-candidate',candidateRegistrationForm,name='registrationForm'),
    path('store-candidate', candidateRegistration,name='storeCandidate'),
    path('login', loginView,name='login'),
    path('home', candidateHome,name='home'),
    path('test-paper', testPaper,name='testPaper'),
    path('calculate-result', calculateTestResult),
    path('test-history', testResultHistory,name='testHistory'),
    path('result', showTestResult),
    path('logout', logoutView,name='logout'),

]

TestingSystem/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTS/',include('OTS.urls')),  
]

OTS/models.py
from django.db import models

class Candidates(models.Model):
    username=models.CharField(primary_key=True,max_length=20)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)

class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)

class result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidates,on_delete=models.CASCADE) 
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.ImageField()
    wrong=models.IntegerField()
    points=models.FloatField()

OTS/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from OTS.models import *


def welcome(request):
    template=loader.get_template('welcome.html')
    return HttpResponse(template.render())
def candidateRegistrationForm(request):
    res=render(request,'registration_form.html')
    return res
def candidateRegistration(request):
    if request.method == "POST":
        username=request.POST['username']
        # check if the user is already exists
        if(len(Candidates.objects.filter(username=username))):
            userStatus=1
        else:
            candidate=Candidates()
            candidate.username=username
            candidate.password=request.POST['password']
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2

    else:
        userStatus=3 #Request method is not POST
    context={
        'userStatus':userStatus
    }
    res=render(request,'registration.html',context)
    return res

def loginView(request):
     if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidates.objects.filter(username=username,password=password)

        if len(candidate)==0:
            loginError="Invalid Username or Password"
            res=render(request,'login.html',{'loginError':loginError})
        else:
            # Login sucess
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name
          #  return redirect ('candidateHome')
            res=HttpResponseRedirect('home')
            return res
     else:
        res= render(request,'login.html')
        return res
     
def candidateHome(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login.html")
    else:
        res=render(request,'home.html')
        return res

def testPaper(request):
    pass
def calculateTestResult(request):
    pass
def testResultHistory(request):
    pass
def showTestResult(request):
    pass
def logoutView(request):
    pass

OTS/templates/home.html
{% extends 'main.html' %}

{% block title %} OTS - Candidate Home page {% endblock title %}
{% block top%}
<a href="{% url 'OTS:home' %}">Signup</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{%endblock %}
{% block content %}

<h1>Welcome {{Request.session.name}}, to your home page</h1>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=1">Test of 1 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=3">Test of 1 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=5">Test of 1 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testHistory'%}"></a>
</div>

{% endblock %}

OTS/templates/login.html
{% extends 'main.html' %}

{% block title %} OTS - Login Form {% endblock title %}
{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>

{%endblock %}
{% block content %}

<div class="all-forms">
    {% if loginError %}
    <div id="error">{{loginError}}</div>

    {% endif %}
    <form action="{% url 'OTS:login' %}" method="post">
        {% csrf_token %}
        <div class="form-unit">
            <label for="username">Username</label>
            <input type="text"name="username">
        </div>
        <div class="form-unit">
            <label for="password">Password</label>
            <input type="password"name="password">
        </div>
        <div class="form-unit">
            <input type="submit"value="Login">
            <input type="reset"value="clear">
        </div>
    </form>
    New user<a href="{% url 'OTS:registrationForm' %}">Click here</a>
</div>


{% endblock %}

OTS/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="top">
        <div class="sitename"><h1>Online Testing System</h1> </div>
        <div class="menu">
            {% block top %}{% endblock %}
        </div>
    </div>
    <div class="content">
        {% block content %}{% endblock%}
    </div>
</body>
</html>

OTS/templates/registration.html
{% extends 'main.html' %}

{% block title %} OTS-Registration Status {% endblock title %}
{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>
<a href="{% url 'OTS:login' %}">Login</a>
{%endblock %}
{% block content %}

{% if userStatus == 1%}
<div class="userStatus">
    Sorry, username is already exist, please try different username
 <a href="{% url 'OTS:registrationForm' %}">Back to candidate registration form</a>
</div>

{% elif userStatus == 2%}
<div class="userStatus">
    Congratulations, user created succesfully
 <a href="{% url 'OTS:login' %}">Login</a>
</div>

{% elif userStatus == 3%}
<div class="userStatus">
    Oops!!. Imprper Request
 <a href="{% url 'OTS:registrationForm' %}">Login</a>
</div>
{% endif %}
{% endblock %}

OTS/templates/registration_form.html
{%extends 'main.html' %}

{% block title %}OTS-Registration Form {% endblock title %}
{% block top%}
<a href="{% url 'OTS:login' %}">Login</a>

{%endblock %}
{% block content %}

<div class="all-forms">
    <form action="{% url 'OTS:storeCandidate'%}" method="post">
        {% csrf_token %}
        <label for="username">username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password"name="password">
        <label for="name">Full Name</label>
        <input type="text"name="name">
        <input type="submit" value="Submit">
        <input type="reset" value="Clear">

    </form>

    Already have an account,<a href="{% url 'OTS:login'%}">Click Here</a>
</div>


{% endblock %}

OTS/templates/welcome.html
{% extends 'main.html' %}

{% block title %} welcome to online Testing System {% endblock title %}
{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>
<a href="{% url 'OTS:login' %}">Login</a>
{%endblock %}
{% block content %}

<P>If you are looking for a modern test management solution, I can recommend test management applicaion.<br>The UI looks clean and friendly to get started with. Import features are easy to understand. Dashboard charts are useful.</P>
<br>
<h4>Over 5000 companies trust our OTS system </h4>


{% endblock %}